impedans_expert/users/urls.py
from django.conf.urls import url

from django.contrib.auth.decorators import login_required

from . views import *

urlpatterns = [
    # url(regex=r'^/$', login_required(UserListView.as_view()), name='list'), # REACTIVATE THIS FOR ADMINS ONLY AFTER PERMISSIONING IS DONE
    url(r'^~redirect/$', login_required(UserRedirectView.as_view()), name='redirect'),
    url(r'^(?P<username>[\w.@+-]+)/$', login_required(UserDetailView.as_view()), name='detail'),
    url(r'^~update/$', login_required(UserUpdateView.as_view()), name='update'),
]
#regex=

impedans_expert/expert/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.postgres.fields import IntegerRangeField
from django.core.urlresolvers import reverse
from impedans_expert.users.models import User
# from impedans_expert.expert_import.models import (
#     Run,
#     RunProperty
# )

class Customer(models.Model):
    company_name    = models.CharField(max_length=100)
    contact_name    = models.CharField(max_length=100)
    contact_email   = models.CharField(max_length=100)
    user            = models.ForeignKey(User)

    @staticmethod
    def get_absolute_url():
        return reverse('details')

    def __str__(self):
        return self.company_name + ', ' + self.contact_name + ' (' + self.contact_email + ')'

    class Meta:
        unique_together=(('contact_email','user'),)

class OwnedModel(models.Model):
    owner = models.ForeignKey(User)

    class Meta:
        abstract = True

class Chamber(models.Model):
    chamber_name    = models.CharField(max_length=100)
    customer        = models.ForeignKey(Customer, on_delete=models.CASCADE)

    @staticmethod
    def get_absolute_url():
        return reverse('details')

    def __str__(self):
        return self.chamber_name

    def __key(self):
        return self.chamber_name, self.customer.id

    def __eq__(self, y):
        return isinstance(y, self.__class__) and self.__key() == y.__key()

    def __hash__(self):
        return hash(self.__key())

    class Meta:
        unique_together=(('chamber_name', 'customer'),)

class ChamberProperty(models.Model):
    chamber         = models.ForeignKey(Chamber, on_delete=models.CASCADE)
    property_name   = models.CharField(max_length=50)
    property_value  = models.CharField(max_length=100)
    user_defined    = models.BooleanField(default=True)

    def __str__(self):
        return self.property_name + ' = ' + self.property_value

    def __key(self):
        return self.chamber, self.property_name

    def __eq__(self, y):
        return isinstance(y, self.__class__) and self.__key() == y.__key()

    def __hash__(self):
        return hash(self.__key())

    class Meta:
        unique_together=(('property_name','property_value', 'chamber'),)


class Marker(models.Model):
    time            = models.DateTimeField()
    chamber         = models.ForeignKey(Chamber, on_delete=models.CASCADE)
    marker_name     = models.CharField(max_length=20)
    marker_string   = models.CharField(max_length=50)

    def __str__(self):
        return str(self.time) + ': ' + self.marker_name + ' = ' + self.marker_string

    def __key(self):
        return self.chamber, self.time, self.marker_name

    def __eq__(self, y):
        return isinstance(y, self.__class__) and self.__key() == y.__key()

    def __hash__(self):
        return hash(self.__key())

    class Meta:
        unique_together=(('time','marker_name', 'chamber'),)


class Recipe(models.Model):
    name        = models.CharField(max_length=255)
    description = models.CharField(max_length=255, blank=True)
    customer    = models.ForeignKey(Customer)

    def __str__(self):
        return str(self.name)

    class Meta:
        unique_together=(('name','customer'),)
    
class RecipeProperties(models.Model):
    recipe          = models.ForeignKey(Recipe)
    property_name   = models.CharField(max_length=255)
    property_value  = models.CharField(max_length=255)

    def __str__(self):
        return str(self.property_name)

    class Meta:
        unique_together=(('recipe','property_name'),)

class Step(models.Model):
    recipe      = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    step_number = models.IntegerField()    # models.IntegerRangeField()

    def __str__(self):
        return str(self.recipe.name + " Step: " + str(self.step_number))

    class Meta:
        unique_together=(('recipe','step_number'),)


class SensorType(models.Model):
    sensor_type = models.CharField(max_length=256)

    def __str__(self):
        return self.sensor_type

    class Meta:
        unique_together=(('sensor_type'),)


class Sensor(models.Model):
    active          = models.BooleanField(default=True)
    chamber         = models.ForeignKey(Chamber, on_delete=models.CASCADE)
    name            = models.CharField(max_length=50, null=False, blank=True)
    serial_number   = models.CharField(max_length=50)
    sensor_type     = models.ForeignKey(SensorType)

    @staticmethod
    def get_absolute_url():
        return reverse('sensor_list')

    def __str__(self):
        return self.serial_number + ' : ' + str(self.chamber_id)

    def __key(self):
        return self.chamber.id, self.serial_number

    def __eq__(self, y):
        return isinstance(y, self.__class__) and self.__key() == y.__key()

    def __hash__(self):
        return hash(self.__key())

    class Meta:
        unique_together=(('serial_number','chamber'),)


class Parameter(models.Model):
    parameter_name          = models.CharField(max_length=50)
    parameter_type          = models.CharField(max_length=30, default='double')
    parameter_unit          = models.CharField(max_length=20, blank=True)

    def __str__(self):
        return self.parameter_name


class SensorParameter(models.Model):
    sensor                  = models.ForeignKey(Sensor)
    parameter               = models.ForeignKey(Parameter)
    parameter_name_userdef  = models.CharField(max_length=100, blank=False, default="Parameter")
    live_value              = models.FloatField(null=True)

    # def save(self, *args, **kwargs):
    #     default_string = str(self.sensor.name + " - " + self.parameter.parameter_name)
    #     self.parameter_name_userdef = default_string
    #     super(SensorParameter, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.sensor.name) + ' - ' + str(self.parameter)

    def __key(self):
        return self.sensor.id, self.parameter.id

    def __eq__(self, y):
        return isinstance(y, self.__class__) and self.__key() == y.__key()

    def __hash__(self):
        return hash(self.__key())

    class Meta:
        unique_together=(('sensor','parameter'),)


class Data(models.Model):
    time                = models.DateTimeField(db_index=True)
    sensor_parameter    = models.ForeignKey(SensorParameter, on_delete=models.CASCADE)
    parameter_value     = models.FloatField()

    def __str__(self):
        return str(self.time) + ' : ' + self.sensor_parameter.parameter_name_userdef + ' = ' + str(self.parameter_value)

    def __key(self):
        return self.time, self.sensor_parameter

    def __eq__(self, y):
        return isinstance(y, self.__class__) and self.__key() == y.__key()

    def __hash__(self):
        return hash(self.__key())

impedans_expert/templates/pages/about.html
{% extends "old_base.html" %}

{% block main_content %}
ABOUT PAGE GOES HERE
{% endblock main_content %}

impedans_expert/templates/pages/chambers.html
{% extends 'old_base.html' %}
{% load staticfiles %}
{% load crispy_forms_filters %}

{% block title %}
Chambers Overview
{% endblock %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
{% endblock %}

{% block main_content %}

<div id="createChamber" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <form class="form-horizontal" id="chamber-form" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="modal-content">
                <div class="modal-header">
                    <h3 id="valueModalTitle">New Chamber</h3>
                </div>
                <div class="modal-body">
                    {% crispy chamber_form %}
                </div>
            </div>
        </form>
    </div>
</div>

<div class="row">
    <div class="col-md-2 p-1">
        <div class="card">
            <h3 class="card-header bg-danger text-white text-center banner">
                Chamber Filter
            </h3>
            <div id="searchBox" class="card-body p-2 text-center mx-auto">
                <h5>Filter by Chamber</h5>
                <div id="filterChamber"></div>
                <hr>
                {% for property in properties %}
                    <h5>Filter by {{property.property_name}}</h5>
                    <div id="filter{{property.id}}"></div>
                    <hr>
                {% endfor %}
                <h5>Filter by Run</h5>
                <div id="filterRun"></div>
                <hr>
                <h5>Filter by Recipe</h5>
                <div id="filterRecipe"></div>
                <hr>
                <h5>Filter by Z-Score</h5>
                <div id="filterZScore"></div>
            </div>
        </div>
    </div>
    
    <div class="col-md-10 p-1">
        <div class="card">
            <div class="card-header text-white text-center p-2 banner">
                <div class="floatLeft">
                    <a href="" data-toggle="modal" data-target="#createChamber"><i class="fas fa-plus-square"></i></a>
                </div>
                <h3>Chambers List</h3>
            </div>
            <div class="card-body p-0">
                <table id="dataTable" class="table table-striped display compact" cellspacing="0" cellpadding="0">
                    <thead>
                        <tr class="table-active">
                            <th>Chamber</th>
                            {% for property in properties %}
                                <th>{{property.property_name}}</th>
                            {% endfor %}
                            <th>Last Run</th>
                            <th>Last Recipe</th>
                            <th>Last Z-Score</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th id="Chamber">Chamber</th>
                            {% for property in properties %}
                                <th id="{{property.id}}">{{property.property_name}}</th>
                            {% endfor %}
                            <th id="Run">Last Run</th>
                            <th id="Recipe">Last Recipe</th>
                            <th id="Z-Score">Last Z-Score</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for chamber, run in chambers_runs_list %}
                            <tr>
                                <td><a href="{% url 'chamber' chamber.id %}">{{chamber.chamber_name}}</a></td>
                                {% for value in chamber.chamberproperty_set.all %}
                                    <td>{{value.property_value}}</td>
                                {% endfor %}
                                {% if run != "No runs yet." %}
                                    <td><a href="{% url 'expert_import:run' run.id %}">{{run}}</a></td>
                                {% else %}
                                    <td><a>{{run}}</a></td>
                                {% endif %}
                                <td><a href="{% url 'chamber' chamber.id %}">{{last_recipe}} - Last recipe for last run?</a></td>
                                <td><a href="{% url 'chamber' chamber.id %}">{{last_z_score}}</a></td>
                            </tr>
                        {% empty %}
                            <div class="card-block p-1 text-center mx-auto">
                                <hr>
                                <h3>No chambers created yet.</h3>
                                <hr>
                                <button class="btn btn-secondary banner new-obj-button" id="create-chamber" data-id="value" data-toggle="modal" data-target="#createChamber">Create New Chamber</button>
                            </div>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>    
</div>
{% endblock %}

{% block end_scripts %}
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="{% static 'js/filter.js' %}"></script>
<script>
    $(document).ready(function() {
        $('#Chamber').appendTo('#filterChamber');
        $('#Run').appendTo('#filterRun');
        $('#Recipe').appendTo('#filterRecipe');
        $('#Z-Score').appendTo('#filterZScore');
        {% for property in properties %}
            var property = "{{property.id}}"
            $('#' + property).appendTo('#filter' + property);
        {% endfor %}
    });
</script>
{% endblock %}

impedans_expert/templates/pages/dashboards.html
{% extends "old_base.html" %}

{% block main_content %}
DASHBOARDS GOES HERE
{% endblock main_content %}

impedans_expert/templates/pages/details.html
{% extends 'old_base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block main_content %}

<div id="graph_display"></div>

<div id="chambers-accordion" role="tablist" aria-multiselectable="true">
    <div class="card">
        <div class="card-header bg-primary text-white" role="tab" id="headingOne">
            <h3 class="mb-0">
                <a id="no-decoration" data-toggle="collapse" data-parent="#chambers-accordion" href="#collapse-chambers" aria-expanded="true" aria-controls="collapse-chambers">
                    Chambers
                </a>
            </h3>
        </div>
        
        <div id="collapse-chambers" class="collapse show" role="tabpanel" aria-labelledby="headingOne">
            <div data-step="1" data-intro="Choose a parameter to graph, and select the pulse position if applicable. If the parsed file is not a pulse file, select None.">
                <label for="parameter-selector">Choose parameter:</label>
                <select id="parameter-selector" name="parameter-selector">
                    {% for parameter in parameters %}
                        <option id="parameter-{{parameter.id}}" value="{{parameter.id}}">{{parameter.parameter_name}}</option>
                    {% endfor %}
                </select>
                at position
                <select id="parameter-selector" name="parameter-selector">
                    {% for position in positions %}
                        <option value="{{parameter_position}}">{{position}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="card-body p-1">
                <table class="table table-hover">
                    <tr class="table-active">
                        <th>Chamber</th>
                        <th class="chamber-width">Sensor</th>
                        <th data-step="3" data-intro="Then click on a run to graph the chosen parameter for that particular run.">Runs</th>
                    </tr>
                    {% for chamber in chambers reversed %}
                        <tr>
                            <td data-step="2" data-intro="Click 'Show Runs' to show a list of runs done on this chamber. The format is 'Run Start Time (Run Duration)'." class="chamber-width">
                                {{chamber}}
                                <button class="btn btn-primary space-this" type="button" data-toggle="collapse" data-target="#collapse{{forloop.counter}}" aria-expanded="false" aria-controls="collapse{{forloop.counter}}">
                                    Show Runs
                                </button>
                            </td>
                            <td>
                                {% for sensor in chamber.sensor_set.all %}
                                    <p data-sensor-id="{{sensor.id}}">
                                        {{sensor.serial_number}}
                                        <div class="input-group input-group-sm">
                                            <input type="text" class="form-control" placeholder="Minutes" name="graph-input">
                                            <span class="input-group-btn">
                                                <button class="btn btn-secondary" type="button">Graph</button>
                                            </span>
                                        </div>
                                    </p>
                                {% empty %}
                                    <p>No sensor assigned to this chamber.</p>
                                {% endfor %}
                            </td>
                            <td>
                                <div class="collapse" id="collapse{{forloop.counter}}">
                                    {% for run in chamber.runs_set.all %}
                                        <p><p id="run-{{forloop.counter}}" data-run-id="{{run.id}}" data-run-start="{{run.start_time|date:'c'}}" data-run-end="{{run.end_time|date:'c'}}">{{forloop.counter}} - {{run}}</p></p>
                                    {% empty %}
                                        <p>No Runs</p>
                                    {% endfor %}
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>
<div id="data-accordion" role="tablist" aria-multiselectable="true">
    <div class="card">
        <div class="card-header bg-primary text-white" role="tab" id="headingTwo" data-step="4" data-intro="Click here to see a list of files that have been uploaded under each chamber, as well as the date and whether the file has been parsed.">
            <h3 class="mb-0">
                <a id="no-decoration" data-toggle="collapse" data-parent="#data-accordion" href="#collapse-files" aria-expanded="true" aria-controls="collapse-files">
                    Uploaded Data
                </a>
            </h3>
        </div>    
        <div id="collapse-files" class="collapse in" role="tabpanel" aria-labelledby="headingTwo">
            <div class="card-body p-1">
                <table class="table table-hover">
                    <tr class="table-active">
                        <th>File</th>
                        <th>Chamber</th>
                        <th>Date added</th>
                        <th>Added</th>
                    </tr>
                    {% for file_upload in files %}
                            <tr>
                                <td>{{file_upload.name}}</td>
                                <td>{{file_upload.chamber}}</td>
                                <td>{{file_upload.date}}</td>
                                {% if file_upload.parsed %}
                                    <td>
                                        <input type="checkbox" checked='checked' onclick="return false;" />
                                    </td>
                                {% elif not file_upload.parsed %}
                                    <td>
                                        <input type="checkbox" onclick="return false;" />
                                    </td>
                                {% endif %}
                            </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}

impedans_expert/templates/pages/home.html
{% extends "old_base.html" %}

{% block main_content %}
HOME GOES HERE
{% endblock main_content %}

impedans_expert/templates/pages/profile.html
{% extends 'old_base.html' %}

{% block main_content %}
<div class="card">
	<h3 class="card-header bg-primary text-white">
		Profile
	</h3>
	<div class="card-body p-0">
		<table class="table table-hover">
			<tr class="table-active">
				<th>Company</th>
				<th>Contact</th>
				<th>Email</th>
				<th>Number of Chambers</th>
			</tr>
			<tr>
				<td>{{customer.company_name}}</td>
				<td>{{customer.contact_name}}</td>
				<td>{{customer.contact_email}}</td>
				<td>{{customer.chamber_set.count}}</td>
			</tr>
		</table>
	</div>
</div>
<hr>
<div class="card">
	<h3 class="card-header bg-primary text-white">
		Chambers
	</h3>
	<div class="card-body p-0">
		<table class="table table-hover">
			<tr class="table-active">
				<th>Name</th>
				<th>Type</th>
				<th>Runs</th>
			</tr>
			<tr>
				{% for chamber in customer.chamber_set.all %}
				<tr>
					<td><a href="{% url 'customers' %}">{{chamber.chamber_name}}</a></td>
					<td><a href="{% url 'customers' %}">{{chamber.runs_set.count}}</a></td>
				</tr>
			{% endfor %}
			</tr>
		</table>
	</div>
</div>
{% endblock %}

impedans_expert/templates/pages/recipes.html
{% extends 'old_base.html' %}
{% load staticfiles %}
{% load crispy_forms_filters %}

{% block title %}
Recipes Overview
{% endblock %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
{% endblock %}

{% block main_content %}

<div id="createChamber" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <form class="form-horizontal" id="chamber-form" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="modal-content">
                <div class="modal-header">
                    <h3 id="valueModalTitle">New Chamber</h3>
                </div>
                <div class="modal-body">
                    {% crispy recipe_form %}
                </div>
            </div>
        </form>
    </div>
</div>

<div class="row">
    <div class="col-md-2 p-1 ">
        <div class="card">
            <h3 class="card-header bg-danger text-white text-center banner">
                Recipe Filter
            </h3>
            <div id="searchBox" class="card-body p-2 text-center mx-auto">
                <h5>Filter by Recipe</h5>
                <div id="filterRecipe"></div>
                <hr>
                <h5>Filter by Description</h5>
                <div id="filterDescription"></div>
                <hr>
                <h5>Filter by Property</h5>
                <div id="filterProperty"></div>
                <hr>
                <h5>Filter by Value</h5>
                <div id="filterValue"></div>
            </div>
        </div>
    </div>
    
    <div class="col-md-10 p-1">
        <div class="card">
            <div class="card-header text-white text-center p-2 banner">
                <div class="floatLeft">
                    <a href="" data-toggle="modal" data-target="#createChamber"><i class="fas fa-plus-square"></i></a>
                </div>
                <h3>Recipes List</h3>
            </div>
            <div class="card-body p-0">
                <table id="dataTable" class="table table-striped display compact">                    
                    <thead>
                        <tr class="table-active">
                            <th>Recipe</th>
                            <th>Description</th>
                            {% for property in properties_list %}
                                <th>{{property.property_name}}</td>
                            {% endfor %}
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th id="Recipe">Recipe</th>
                            <th id="Description">Description</th>
                            <th id="Property">Property</th>
                            <th id="Value">Value</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for recipe in recipes_list %}
                            <tr>
                                <td><a href="{% url 'recipe' recipe.id %}">{{recipe}}</a></td>
                                <td>{{recipe.description}}</td>
                                {% for property in properties_list %}
                                    <td>{{property.property_value}}</td>
                                {% endfor %}
                            </tr>
                        {% empty %}
                            <div class="card-block p-1 text-center mx-auto">
                                <hr>
                                <h3>No recipes created yet.</h3>
                                <hr>
                                <button class="btn btn-secondary banner new-obj-button" id="create-recipe" data-id="value" data-toggle="modal" data-target="#createRecipe">Create New Recipe</button>
                            </div>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>    
</div>
{% endblock %}

{% block end_scripts %}
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="{% static 'js/filter.js' %}"></script>
<script>
    $(document).ready(function() {
        $('#Recipe').appendTo('#filterRecipe');
        $('#Description').appendTo('#filterDescription');
        $('#Property').appendTo('#filterProperty');
        $('#Value').appendTo('#filterValue');
    });
</script>
{% endblock %}

impedans_expert/templates/pages/reports.html
{% extends "old_base.html" %}

{% block main_content %}
REPORTS GOES HERE
{% endblock main_content %}

impedans_expert/templates/pages/runs.html
{% extends 'old_base.html' %}
{% load staticfiles %}
{% load crispy_forms_filters %}

{% block title %}
Runs Overview
{% endblock %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
{% endblock %}

{% block main_content %}
<div class="row">
	<div class="col-md-2 p-1 ">
		<div class="card">
			<h3 class="card-header bg-danger text-white text-center banner">
				Run Filter
			</h3>
			<div id="searchBox" class="card-body p-2 text-center mx-auto">
				<h5>Filter by Date</h5>
				<div id="filterDate"></div>
				<hr>
				<h5>Filter by Chamber</h5>
				<div id="filterChamber"></div>
				<hr>
				<h5>Filter by Run Length</h5>
				<div id="filterLength"></div>
				<hr>
				<h5>Filter by Recipe</h5>
				<div id="filterRecipe"></div>
				<hr>
				<h5>Filter by Z-Score</h5>
				<div id="filterZScore"></div>
			</div>
		</div>
	</div>
	
	<div class="col-md-10 p-1">
		<div class="card">
			<div class="card-header text-white text-center p-2 banner">
				<div id="graphRuns" class="floatLeft" hidden>
					<a id="chartTheseRuns" href=""><i class="fas fa-chart-line"></i></a>
				</div>
				<h3>Runs List</h3>
			</div>
			<div class="card-body p-0">
				<table id="dataTable" class="table table-striped display compact">                    
					<thead>
						<tr class="table-active">
							<th></th>
							<th>Date</th>
							<th>Chamber</th>
							<th>Run Length</th>
							<th>Last Recipe</th>
							<th>Last Z-Score</th>
						</tr>
					</thead>
					<tfoot>
						<tr>
							<th id="hide"></th>
							<th id="Date">Date</th>
							<th id="Chamber">Chamber</th>
							<th id="Length">Run Length</th>
							<th id="Recipe">Last Recipe</th>
							<th id="Z-Score">Last Z-Score</th>
						</tr>
					</tfoot>
					<tbody>
						{% for run, length in runs_lengths_list %}
							<tr>
								<td><input class="checkboxRun" data-run_id="{{run.id}}" type="checkbox"></td>
								<td><a href="{% url 'expert_import:run' run.id %}">{{run.start_time}}</a></td>
								<td><a href="{% url 'chamber' run.chamber.id %}">{{run.chamber}}</a></td>
								<td><a {% comment %} href="{% url 'sensor' sensor.id %}" {% endcomment %}>{{length}}</a></td>
								<td><a {% comment %} href="{% url 'sensor' sensor.id %}" {% endcomment %}>{{run.recipe}}</a></td>
								<td><a {% comment %} href="{% url 'sensor' sensor.id %}" {% endcomment %}>{{last_z_score}}</a></td>
							</tr>
						{% empty %}
							<div class="card-block p-1 text-center mx-auto">
                                <hr>
                                <h3>No run data gathered yet.</h3>
                                <hr>
                            </div>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>    
</div>
{% endblock %}

{% block end_scripts %}
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="{% static 'js/filter.js' %}"></script>
<script>
	$(document).ready(function() {
		$('#hide').hide();
		$('#Date').appendTo('#filterDate');
		$('#Chamber').appendTo('#filterChamber');
		$('#Length').appendTo('#filterLength');
		$('#Recipe').appendTo('#filterRecipe');
		$('#Z-Score').appendTo('#filterZScore');

		var choiceContainer = $("#dataTable");
		
		var countChecked = function () {
			var n = choiceContainer.find("input:checked").length;
			if (n >= 1) {
				$("#graphRuns").attr("hidden", false);
			} else {
				$("#graphRuns").attr("hidden", true);
			}
		};
		
		countChecked();

		$("input[type=checkbox]").on("click", countChecked);

		$("#graphRuns").click(function() {
			var ids_list = new Array();

			function generateLink(ids_list) {
				var url = "{% url 'expert_import:chart_runs' %}";
				url += "?id=" + ids_list.join('&id=');
				return url;
			};

			choiceContainer.find("input:checked").each(function() {
				var run_id = $(this).data("run_id");
				ids_list.push(run_id);
			});

			$("#chartTheseRuns").attr("href", generateLink(ids_list));
		});
	});
</script>
{% endblock %}