impedans_expert/expert/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.views import defaults as default_views
from django.views.generic import TemplateView, RedirectView

from impedans_expert.expert import views

urlpatterns = [
    #url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', auth_views.login, name='account_login'),
    url(r'^logout/$', login_required(auth_views.logout), {'next_page': 'account_login'}, name='logout'),
    url(r'^$', login_required(views.DetailsView.as_view()), name='home'),
    url(r'^details/$', login_required(views.DetailsView.as_view()), name='details'),
    url(r'^profile/$', login_required(views.ProfileView.as_view()), name='profile'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^live/$', login_required(views.LiveView.as_view()), name='live'),

    # url(r'^(?P<customer_id>[0-9]+)/$', views.customers, name='customers'),
    url(r'^customer/$', login_required(views.CustomerView.as_view()), name='customers'),
    url(r'^chamberinfo/(?P<chamber_id>[0-9]+)/$', login_required(views.ChamberInfoView.as_view()), name='chamber'),

    url(r'^parameters/$', login_required(views.ParameterView.as_view()), name='parameters'),
    url(r'^sensorlist/$', login_required(views.SensorListView), name='sensor_list'),
    url(r'^chamberlist/$', login_required(views.ChamberListView), name='chamber_list'),
    url(r'^recipelist/$', login_required(views.RecipeListView.as_view()), name='recipe_list'),

    # url(r'^customer/add/$', login_required(views.CustomerCreate.as_view()), name='customer-add'),
    url(r'^chamber/add/$', login_required(views.chamberCreate), name='chamber-add'),
    url(r'^sensor/add/$', login_required(views.SensorCreate.as_view()), name='sensor-add'),
    url(r'^sensors/(?P<sensor_id>[0-9]+)/$', login_required(views.SensorInfoView.as_view()), name='sensor'),

    url(r'^api/', include('expert_import.api.urls', namespace='import_api')),
    url(r'^api/', include('expert.api.urls', namespace='expert_api')),
    url(r'^api/', include('expert_algorithms.api.urls', namespace='algorithms_api')),
    url(r'^api/', include('users.api.urls', namespace='users_api')),

    # url(r'^sensors/$', login_required(views.sensors), name='Sensors'),
    # url(r'^chambers/$', login_required(views.chambers), name='Chambers'),
    url(r'^files/$', login_required(views.files), name='Files'),
    url(r'^filetypes/$', login_required(views.filetypes), name='FileTypes'),

    url(r'^home/$', login_required(views.HomeView.as_view()), name='home'),
    url(r'^chambers/$', login_required(views.ChambersView.as_view()), name='chambers'),
    url(r'^sensors/$', login_required(views.SensorsView.as_view()), name='sensors'),
    url(r'^sensors_live/(?P<sensor_id>[0-9]+)/$', login_required(views.SensorLiveValues), name='live_values'),

    url(r'^recipes/$', login_required(views.RecipesView.as_view()), name='recipes'),
    url(r'^recipes/(?P<recipe_id>[0-9]+)/$', login_required(views.RecipeInfoView.as_view()), name='recipe'),
    url(r'^recipes/(?P<recipe_id>[0-9]+)/algorithm_(?P<slug>[\w-]+)/$', login_required(views.RecipeConfigView.as_view()), name='recipe_config'),
    url(r'^recipes/(?P<recipe_id>[0-9]+)/(?P<stream_algorithm_id>[0-9]+)_algorithm_(?P<slug>[\w-]+)/baselines$', login_required(views.BaselineConfigView.as_view()), name='baseline_config'),
    url(r'^recipes/runs-table/(?P<chamber_id>[0-9]+)/$', login_required(views.RunsTableView), name='runs_table'),

    url(r'^runs/$', login_required(views.RunsView.as_view()), name='runs'),
    url(r'^reports/$', login_required(views.ReportsView.as_view()), name='reports'),
    url(r'^dashboards/$', login_required(views.DashboardsView.as_view()), name='dashboards'),
]

impedans_expert/users/urls.py
from django.conf.urls import url

from django.contrib.auth.decorators import login_required

from . views import *

urlpatterns = [
    # url(regex=r'^/$', login_required(UserListView.as_view()), name='list'), # REACTIVATE THIS FOR ADMINS ONLY AFTER PERMISSIONING IS DONE
    url(r'^~redirect/$', login_required(UserRedirectView.as_view()), name='redirect'),
    url(r'^(?P<username>[\w.@+-]+)/$', login_required(UserDetailView.as_view()), name='detail'),
    url(r'^~update/$', login_required(UserUpdateView.as_view()), name='update'),
]
#regex=

impedans_expert/templates/403_csrf.html
{% extends "old_base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

impedans_expert/templates/base.html
{% load staticfiles i18n compress%}<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="x-ua-compatible" content="ie=edge">
		<title>{% block title %}Impedans Expert{% endblock title %}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<meta name="author" content="">
		<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
		<![endif]-->

		{% block css %}
		<!-- Latest compiled and minified Bootstrap 4 Alpha 4 CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

		<!-- Your stuff: Third-party CSS libraries go here -->
		<link href="{% static 'tellme/feedback.min.css' %}" rel="stylesheet">

		{% compress css %}
		<!-- This file stores project-specific CSS -->
		<link href="{% static 'css/project.css' %}" rel="stylesheet">
		{% endcompress %}
		{% endblock %}

	</head>

	<body>

		<div id="wrap">
			{% block banner %}
			<div class="m-b-1">
				<nav class="navbar expert_navbar navbar-expand-md navbar-light bg-light">
					<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'expert/images/impedans_login.png' %}" width="20" height="30" alt=""></a>

					<div class="collapse navbar-collapse" id="navbarSupportedContent">
						{% block nav_menu %}
						{% url 'expert:home' as home %}
						{% url 'expert_upload:File_Upload-add' as file_upload %}
						{% url 'expert_document:Document_Upload-add' as documents %}

						<ul class="navbar-nav mr-auto">

							<li class="nav-item {% if request.path == home %} active{% endif %}">
								{# URL provided by expert/urls.py #}
								<a class="nav-link" href="{{home}}">Home {% if request.path == home %} <span class="sr-only">(current)</span>{% endif %}</a>
							</li>

							<li class="nav-item{% if request.path == file_upload %} active{% endif %}">
								{# URL provided by expert/urls.py #}
								<a class="nav-link" href="{{file_upload}}">Upload Data{% if request.path == file_upload %} <span class="sr-only">(current)</span>{% endif %}</a>
							</li>

							<li class="nav-item{% if request.path == documents %} active{% endif %}">
								{# URL provided by expert/urls.py #}
								<a class="nav-link" href="{{documents}}">Documents{% if request.path == documents %} <span class="sr-only">(current)</span>{% endif %}</a>
							</li>

						</ul>
						{# URL provided by django-allauth/account/urls.py #}
						<a class="nav-item" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a> {% endblock %}

					</div> <!-- /navbarSupportedContent -->
				</nav>

			</div>  <!-- /m-b-1 -->
			{% endblock banner %}

			<div class="container">
				{% if messages %}
						{% for message in messages %}
								<div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
						{% endfor %}
				{% endif %}

				{% block content %}
					<p>This is the main page content.</p>
				{% endblock content %}

			</div> <!-- /container -->

		</div> <!-- /wrap -->

		<div id="footer">
				 <p>Copyright © 2017 <a style="text-decoration: none" href="http://www.impedans.com/">Impedans Ltd.</a> All rights reserved.</p>
		</div>

	<button type="button" id="feedback-btn" class="btn btn-info vertical-right-aligned">
 	 Feedback </button>

		{% block modal %}{% endblock modal %}


		<!-- Javascript
		================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->

		{% block javascript %}
			<!-- Required by Bootstrap v4 Alpha 4 -->
			<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
			<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

			<!-- Your stuff: Third-party javascript libraries go here -->

			<!-- place project specific Javascript in this file -->
			{% compress js %}
			<script src="{% static 'js/project.js' %}"></script>
			{% endcompress %}

		{% endblock javascript %}
		{% include 'tellme/js_inc.html' %}
	</body>
</html>

impedans_expert/templates/old_base.html
{% load staticfiles %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>Impedans Expert - {% block title %}{% endblock %}</title>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dc/2.1.9/dc.min.css" integrity="sha256-WHvgKNpdomdSPf4EGBla0Wx7QZpnZyKAOvuHQcuMHNs=" crossorigin="anonymous" />
		<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" media="all" />
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css" />
		<link rel="stylesheet" type="text/css" href="{% static 'expert/style.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/introjs.min.css' %}" />

		<!--[if lte IE 8]><script language="javascript" type="text/javascript" src="excanvas.min.js"></script><![endif]-->

		<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
		<script>window.jQuery || document.write('<script src="/static/script/jquery-3.2.1.min.js"><\/script>')</script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/file-uploader/5.13.0/fine-uploader.min.js"></script>
		<!-- Cookies.js, so we can get the CSRFToken cookie -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.1.3/js.cookie.min.js" charset="utf-8"></script>
		<script src="http://d3js.org/d3.v3.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/crossfilter/1.3.12/crossfilter.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/dc/2.1.9/dc.js"></script>

		<!-- FontAwesome for button styles and icons -->
		<script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>

		<!-- moment.js for time picker and easy date range object conversion -->
		<script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>

		<!-- Include Date Range Picker script and style sheet-->
		<script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>
		<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />

		{% block styles %}
		{% endblock %}

	</head>
	<body>
		<div id="wrap">

			<!-- Begin Navbar -->

			<nav class="navbar navbar-expand-sm expert_navbar">
				<div class="container-fluid">
					<a class="navbar-brand" href="#"><img src="{% static 'expert/images/impedans_login.png' %}" width="20" height="30" alt=""></a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarExpertMenu" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarExpertMenu">

						{% block nav_menu %}

						<ul class="navbar-nav nav-tabs mr-auto">							
							{% url 'details' as details %}
							{% url 'expert_upload:File_Upload-add' as file_upload %}
							{% url 'expert_documents:Document_Upload-add' as documents %}
							{% url 'expert_import:Parse' as parse_file %}
							{% url 'expert_algorithms:algorithm_selector' as algorithm_select %}
							{% url 'expert_algorithms:results_display' as results_display %}
							{% url 'expert_algorithms:trainer' as trainer %}
							{% url 'expert:profile' as profile %}
							{% url 'about' as about %}
							{% url 'live' as live %}

							<li class="nav-item">
								<a class="nav-link {% if request.path == home %} active {% endif %}" href={% url 'home' %}>Home{% if request.path == home %} <span class="sr-only">(current)</span>{% endif %}</a>
							</li>
							<li class="nav-item">
								<a class="nav-link {% if request.path == chambers %} active {% endif %}" href={% url 'chambers' %}>Chambers{% if request.path == chambers %} <span class="sr-only">(current)</span>{% endif %}</a>
							</li>
							<li class="nav-item">
								<a class="nav-link {% if request.path == sensors %} active {% endif %}" href={% url 'sensors' %}>Sensors{% if request.path == sensors %} <span class="sr-only">(current)</span>{% endif %}</a>
							</li>
							<li class="nav-item">
								<a class="nav-link {% if request.path == recipes %} active {% endif %}" href={% url 'recipes' %}>Recipes{% if request.path == recipes %} <span class="sr-only">(current)</span>{% endif %}</a>
							</li>
							<li class="nav-item">
								<a class="nav-link {% if request.path == runs %} active {% endif %}" href={% url 'runs' %}>Runs{% if request.path == runs %} <span class="sr-only">(current)</span>{% endif %}</a>
							</li>
							<li class="nav-item">
								<a class="nav-link {% if request.path == reports %} active {% endif %}" href={% url 'reports' %}>Reports{% if request.path == reports %} <span class="sr-only">(current)</span>{% endif %}</a>
							</li>
							<li class="nav-item">
								<a class="nav-link {% if request.path == dashboards %} active {% endif %}" href={% url 'dashboards' %}>Dashboards{% if request.path == dashboards %} <span class="sr-only">(current)</span>{% endif %}</a>
							</li>
							<li class="nav-item">
								<a class="nav-link {% if request.path == live %} active {% endif %}" href="{{live}}">Live{% if request.path == live %} <span class="sr-only">(current)</span>{% endif %}</a>
							</li>
						</ul>
						<ul class="navbar-nav nav-tabs mr-right">

								{% if request.path == "/expert/details/" %}
								<li class="nav-item">
									<a class="btn btn-sm btn-info" role="button" id="help-button" href="javascript:void(0);" onclick="javascript:introJs().start();">Help</a>
								</li>
								{% endif %}

								<li class="nav-item">
									<a class="nav-link {% if request.path == about %} active {% endif %}" href="{{about}}">About{% if request.path == about %} <span class="sr-only">(current)</span>{% endif %}</a>
								</li>
							<li class="nav-item dropdown justify-content-end">
								<a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

									{% if user.is_authenticated %}
										<span class="caret"> {{ user }}</span>
									{% else %}
										<span class="caret"> Log in </span>
									{% endif %}

								</a>

								{% if user.is_authenticated %}

								<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
									<a class="dropdown-item" href="{% url 'profile' %}">Profile</a>
									<a class="dropdown-item" href="{% url 'chamber_list' %}">Chamber List</a>
									<a class="dropdown-item" href="{% url 'sensor_list' %}">Sensor List</a>
									<a class="dropdown-item" href="{% url 'recipe_list' %}">Recipe List</a>
									<a class="dropdown-item" href="{% url 'expert_import:runs' %}">Run List</a>
									<a class="dropdown-item" href="{% url 'chamber-add' %}">Add Chamber</a>
									<a class="dropdown-item" href="{% url 'sensor-add' %}">Add Sensor</a>
									<a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
									<hr>
									<a class="dropdown-item" href="{{details}}">Details</a>
									<a class="dropdown-item" href="{{file_upload}}">Upload Data</a>
									<a class="dropdown-item" href="{{documents}}">Documents</a>
									<a class="dropdown-item" href="{{parse_file}}">Parse Files</a>
									<a class="dropdown-item" href="{{algorithm_select}}">Algorithm Select</a>
									<a class="dropdown-item" href="{{trainer}}">Training</a>
									<a class="dropdown-item" href="{{results_display}}">Results</a>
									<a class="dropdown-item" href="{{live}}">Live</a>
								</div>

								{% endif %}

							</li>
						</ul>

						{% endblock %}

					</div>
				</div>
			</nav>

			<!-- End Navbar -->

			<main>
				<div class="container-fluid p-3">

					{% block main_content %}
					{% endblock %}

				</div>
			</main>
		</div>

		<!-- Begin Footer -->

		<div id="footer">
			<p>Copyright © 2017 <a style="text-decoration: none" href="http://www.impedans.com/">Impedans Ltd.</a> All rights reserved.</p>
		</div>

		<!-- End Footer -->

		
		<script src="{% static 'js/intro.min.js' %}"></script>
		<script src="{% static 'js/project.js' %}"></script>
		<script src="{% static 'js/graphs.js' %}"></script>
		
		{% block end_scripts %}
		{% endblock %}		

	</body>
</html>