impedans_expert/expert/api/urls.py
from django.conf.urls import url
from django.contrib import admin

from expert.api.views import (
    ChamberCreateAPIView,
    ChamberDeleteAPIView,
    ChamberDetailAPIView,
    ChamberListAPIView,
    ChamberUpdateAPIView,
    ChamberPropertiesCreateAPIView,
    ChamberPropertiesDeleteAPIView,
    ChamberPropertiesDetailAPIView,
    ChamberPropertiesListAPIView,
    ChamberPropertiesUpdateAPIView,
    CustomerCreateAPIView,
    CustomerDeleteAPIView,
    CustomerDetailAPIView,
    CustomerListAPIView,
    CustomerUpdateAPIView,
    DataCreateAPIView,
    DataDeleteAPIView,
    DataDetailAPIView,
    DataListAPIView,
    DataUpdateAPIView,
    MarkerCreateAPIView,
    MarkerDeleteAPIView,
    MarkerDetailAPIView,
    MarkerListAPIView,
    MarkerUpdateAPIView,
    ParameterCreateAPIView,
    ParameterDeleteAPIView,
    ParameterDetailAPIView,
    ParameterListAPIView,
    ParameterUpdateAPIView,
    SensorCreateAPIView,
    SensorDeleteAPIView,
    SensorDetailAPIView,
    SensorListAPIView,
    SensorUpdateAPIView,
    SensorTypeCreateAPIView,
    SensorTypeDeleteAPIView,
    SensorTypeDetailAPIView,
    SensorTypeListAPIView,
    SensorTypeUpdateAPIView,
)

urlpatterns = [
    url(r'^chamber/$', ChamberListAPIView.as_view(), name='chamber_list'),
    url(r'^chamber/create/$', ChamberCreateAPIView.as_view(), name='chamber_list_create'),
    url(r'^chamber/(?P<pk>\d+)/$', ChamberDetailAPIView.as_view(), name='chamber_list_detail'),
    url(r'^chamber/(?P<pk>\d+)/edit/$', ChamberUpdateAPIView.as_view(), name='chamber_list_update'),
    url(r'^chamber/(?P<pk>\d+)/delete/$', ChamberDeleteAPIView.as_view(), name='chamber_list_delete'),

    url(r'^chamber-properties/$', ChamberPropertiesListAPIView.as_view(), name='chamber_properties_list'),
    url(r'^chamber-properties/create/$', ChamberPropertiesCreateAPIView.as_view(), name='chamber_properties_list_create'),
    url(r'^chamber-properties/(?P<pk>\d+)/$', ChamberPropertiesDetailAPIView.as_view(), name='chamber_properties_list_detail'),
    url(r'^chamber-properties/(?P<pk>\d+)/edit/$', ChamberPropertiesUpdateAPIView.as_view(), name='chamber_properties_list_update'),
    url(r'^chamber-properties/(?P<pk>\d+)/delete/$', ChamberPropertiesDeleteAPIView.as_view(), name='chamber_properties_list_delete'),

    url(r'^customer/$', CustomerListAPIView.as_view(), name='customer_list'),
    url(r'^customer/create/$', CustomerCreateAPIView.as_view(), name='customer_list_create'),
    url(r'^customer/(?P<pk>\d+)/$', CustomerDetailAPIView.as_view(), name='customer_list_detail'),
    url(r'^customer/(?P<pk>\d+)/edit/$', CustomerUpdateAPIView.as_view(), name='customer_list_update'),
    url(r'^customer/(?P<pk>\d+)/delete/$', CustomerDeleteAPIView.as_view(), name='customer_list_delete'),

    url(r'^data/$', DataListAPIView.as_view(), name='data_list'),
    url(r'^data/create/$', DataCreateAPIView.as_view(), name='data_list_create'),
    url(r'^data/(?P<pk>\d+)/$', DataDetailAPIView.as_view(), name='data_list_detail'),
    url(r'^data/(?P<pk>\d+)/edit/$', DataUpdateAPIView.as_view(), name='data_list_update'),
    url(r'^data/(?P<pk>\d+)/delete/$', DataDeleteAPIView.as_view(), name='data_list_delete'),

    url(r'^marker/$', MarkerListAPIView.as_view(), name='marker_list'),
    url(r'^marker/create/$', MarkerCreateAPIView.as_view(), name='marker_list_create'),
    url(r'^marker/(?P<pk>\d+)/$', MarkerDetailAPIView.as_view(), name='marker_list_detail'),
    url(r'^marker/(?P<pk>\d+)/edit/$', MarkerUpdateAPIView.as_view(), name='marker_list_update'),
    url(r'^marker/(?P<pk>\d+)/delete/$', MarkerDeleteAPIView.as_view(), name='marker_list_delete'),

    url(r'^parameter/$', ParameterListAPIView.as_view(), name='parameter_list'),
    url(r'^parameter/create/$', ParameterCreateAPIView.as_view(), name='parameter_list_create'),
    url(r'^parameter/(?P<pk>\d+)/$', ParameterDetailAPIView.as_view(), name='parameter_list_detail'),
    url(r'^parameter/(?P<pk>\d+)/edit/$', ParameterUpdateAPIView.as_view(), name='parameter_list_update'),
    url(r'^parameter/(?P<pk>\d+)/delete/$', ParameterDeleteAPIView.as_view(), name='parameter_list_delete'),

    url(r'^sensor/$', SensorListAPIView.as_view(), name='sensor_list'),
    url(r'^sensor/create/$', SensorCreateAPIView.as_view(), name='sensor_list_create'),
    url(r'^sensor/(?P<pk>\d+)/$', SensorDetailAPIView.as_view(), name='sensor_list_detail'),
    url(r'^sensor/(?P<pk>\d+)/edit/$', SensorUpdateAPIView.as_view(), name='sensor_list_update'),
    url(r'^sensor/(?P<pk>\d+)/delete/$', SensorDeleteAPIView.as_view(), name='sensor_list_delete'),

    url(r'^sensor-type/$', SensorTypeListAPIView.as_view(), name='sensor_type_list'),
    url(r'^sensor-type/create/$', SensorTypeCreateAPIView.as_view(), name='sensor_type_list_create'),
    url(r'^sensor-type/(?P<pk>\d+)/$', SensorTypeDetailAPIView.as_view(), name='sensor_type_list_detail'),
    url(r'^sensor-type/(?P<pk>\d+)/edit/$', SensorTypeUpdateAPIView.as_view(), name='sensor_type_list_update'),
    url(r'^sensor-type/(?P<pk>\d+)/delete/$', SensorTypeDeleteAPIView.as_view(), name='sensor_type_list_delete'),
]

impedans_expert/expert/urls.py
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.views import defaults as default_views
from django.views.generic import TemplateView, RedirectView

from impedans_expert.expert import views

urlpatterns = [
    #url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', auth_views.login, name='account_login'),
    url(r'^logout/$', login_required(auth_views.logout), {'next_page': 'account_login'}, name='logout'),
    url(r'^$', login_required(views.DetailsView.as_view()), name='home'),
    url(r'^details/$', login_required(views.DetailsView.as_view()), name='details'),
    url(r'^profile/$', login_required(views.ProfileView.as_view()), name='profile'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^live/$', login_required(views.LiveView.as_view()), name='live'),

    # url(r'^(?P<customer_id>[0-9]+)/$', views.customers, name='customers'),
    url(r'^customer/$', login_required(views.CustomerView.as_view()), name='customers'),
    url(r'^chamberinfo/(?P<chamber_id>[0-9]+)/$', login_required(views.ChamberInfoView.as_view()), name='chamber'),

    url(r'^parameters/$', login_required(views.ParameterView.as_view()), name='parameters'),
    url(r'^sensorlist/$', login_required(views.SensorListView), name='sensor_list'),
    url(r'^chamberlist/$', login_required(views.ChamberListView), name='chamber_list'),
    url(r'^recipelist/$', login_required(views.RecipeListView.as_view()), name='recipe_list'),

    # url(r'^customer/add/$', login_required(views.CustomerCreate.as_view()), name='customer-add'),
    url(r'^chamber/add/$', login_required(views.chamberCreate), name='chamber-add'),
    url(r'^sensor/add/$', login_required(views.SensorCreate.as_view()), name='sensor-add'),
    url(r'^sensors/(?P<sensor_id>[0-9]+)/$', login_required(views.SensorInfoView.as_view()), name='sensor'),

    url(r'^api/', include('expert_import.api.urls', namespace='import_api')),
    url(r'^api/', include('expert.api.urls', namespace='expert_api')),
    url(r'^api/', include('expert_algorithms.api.urls', namespace='algorithms_api')),
    url(r'^api/', include('users.api.urls', namespace='users_api')),

    # url(r'^sensors/$', login_required(views.sensors), name='Sensors'),
    # url(r'^chambers/$', login_required(views.chambers), name='Chambers'),
    url(r'^files/$', login_required(views.files), name='Files'),
    url(r'^filetypes/$', login_required(views.filetypes), name='FileTypes'),

    url(r'^home/$', login_required(views.HomeView.as_view()), name='home'),
    url(r'^chambers/$', login_required(views.ChambersView.as_view()), name='chambers'),
    url(r'^sensors/$', login_required(views.SensorsView.as_view()), name='sensors'),
    url(r'^sensors_live/(?P<sensor_id>[0-9]+)/$', login_required(views.SensorLiveValues), name='live_values'),

    url(r'^recipes/$', login_required(views.RecipesView.as_view()), name='recipes'),
    url(r'^recipes/(?P<recipe_id>[0-9]+)/$', login_required(views.RecipeInfoView.as_view()), name='recipe'),
    url(r'^recipes/(?P<recipe_id>[0-9]+)/algorithm_(?P<slug>[\w-]+)/$', login_required(views.RecipeConfigView.as_view()), name='recipe_config'),
    url(r'^recipes/(?P<recipe_id>[0-9]+)/(?P<stream_algorithm_id>[0-9]+)_algorithm_(?P<slug>[\w-]+)/baselines$', login_required(views.BaselineConfigView.as_view()), name='baseline_config'),
    url(r'^recipes/runs-table/(?P<chamber_id>[0-9]+)/$', login_required(views.RunsTableView), name='runs_table'),

    url(r'^runs/$', login_required(views.RunsView.as_view()), name='runs'),
    url(r'^reports/$', login_required(views.ReportsView.as_view()), name='reports'),
    url(r'^dashboards/$', login_required(views.DashboardsView.as_view()), name='dashboards'),
]

impedans_expert/users/urls.py
from django.conf.urls import url

from django.contrib.auth.decorators import login_required

from . views import *

urlpatterns = [
    # url(regex=r'^/$', login_required(UserListView.as_view()), name='list'), # REACTIVATE THIS FOR ADMINS ONLY AFTER PERMISSIONING IS DONE
    url(r'^~redirect/$', login_required(UserRedirectView.as_view()), name='redirect'),
    url(r'^(?P<username>[\w.@+-]+)/$', login_required(UserDetailView.as_view()), name='detail'),
    url(r'^~update/$', login_required(UserUpdateView.as_view()), name='update'),
]
#regex=

impedans_expert/expert/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.postgres.fields import IntegerRangeField
from django.core.urlresolvers import reverse
from impedans_expert.users.models import User
# from impedans_expert.expert_import.models import (
#     Run,
#     RunProperty
# )

class Customer(models.Model):
    company_name    = models.CharField(max_length=100)
    contact_name    = models.CharField(max_length=100)
    contact_email   = models.CharField(max_length=100)
    user            = models.ForeignKey(User)

    @staticmethod
    def get_absolute_url():
        return reverse('details')

    def __str__(self):
        return self.company_name + ', ' + self.contact_name + ' (' + self.contact_email + ')'

    class Meta:
        unique_together=(('contact_email','user'),)

class OwnedModel(models.Model):
    owner = models.ForeignKey(User)

    class Meta:
        abstract = True

class Chamber(models.Model):
    chamber_name    = models.CharField(max_length=100)
    customer        = models.ForeignKey(Customer, on_delete=models.CASCADE)

    @staticmethod
    def get_absolute_url():
        return reverse('details')

    def __str__(self):
        return self.chamber_name

    def __key(self):
        return self.chamber_name, self.customer.id

    def __eq__(self, y):
        return isinstance(y, self.__class__) and self.__key() == y.__key()

    def __hash__(self):
        return hash(self.__key())

    class Meta:
        unique_together=(('chamber_name', 'customer'),)

class ChamberProperty(models.Model):
    chamber         = models.ForeignKey(Chamber, on_delete=models.CASCADE)
    property_name   = models.CharField(max_length=50)
    property_value  = models.CharField(max_length=100)
    user_defined    = models.BooleanField(default=True)

    def __str__(self):
        return self.property_name + ' = ' + self.property_value

    def __key(self):
        return self.chamber, self.property_name

    def __eq__(self, y):
        return isinstance(y, self.__class__) and self.__key() == y.__key()

    def __hash__(self):
        return hash(self.__key())

    class Meta:
        unique_together=(('property_name','property_value', 'chamber'),)


class Marker(models.Model):
    time            = models.DateTimeField()
    chamber         = models.ForeignKey(Chamber, on_delete=models.CASCADE)
    marker_name     = models.CharField(max_length=20)
    marker_string   = models.CharField(max_length=50)

    def __str__(self):
        return str(self.time) + ': ' + self.marker_name + ' = ' + self.marker_string

    def __key(self):
        return self.chamber, self.time, self.marker_name

    def __eq__(self, y):
        return isinstance(y, self.__class__) and self.__key() == y.__key()

    def __hash__(self):
        return hash(self.__key())

    class Meta:
        unique_together=(('time','marker_name', 'chamber'),)


class Recipe(models.Model):
    name        = models.CharField(max_length=255)
    description = models.CharField(max_length=255, blank=True)
    customer    = models.ForeignKey(Customer)

    def __str__(self):
        return str(self.name)

    class Meta:
        unique_together=(('name','customer'),)
    
class RecipeProperties(models.Model):
    recipe          = models.ForeignKey(Recipe)
    property_name   = models.CharField(max_length=255)
    property_value  = models.CharField(max_length=255)

    def __str__(self):
        return str(self.property_name)

    class Meta:
        unique_together=(('recipe','property_name'),)

class Step(models.Model):
    recipe      = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    step_number = models.IntegerField()    # models.IntegerRangeField()

    def __str__(self):
        return str(self.recipe.name + " Step: " + str(self.step_number))

    class Meta:
        unique_together=(('recipe','step_number'),)


class SensorType(models.Model):
    sensor_type = models.CharField(max_length=256)

    def __str__(self):
        return self.sensor_type

    class Meta:
        unique_together=(('sensor_type'),)


class Sensor(models.Model):
    active          = models.BooleanField(default=True)
    chamber         = models.ForeignKey(Chamber, on_delete=models.CASCADE)
    name            = models.CharField(max_length=50, null=False, blank=True)
    serial_number   = models.CharField(max_length=50)
    sensor_type     = models.ForeignKey(SensorType)

    @staticmethod
    def get_absolute_url():
        return reverse('sensor_list')

    def __str__(self):
        return self.serial_number + ' : ' + str(self.chamber_id)

    def __key(self):
        return self.chamber.id, self.serial_number

    def __eq__(self, y):
        return isinstance(y, self.__class__) and self.__key() == y.__key()

    def __hash__(self):
        return hash(self.__key())

    class Meta:
        unique_together=(('serial_number','chamber'),)


class Parameter(models.Model):
    parameter_name          = models.CharField(max_length=50)
    parameter_type          = models.CharField(max_length=30, default='double')
    parameter_unit          = models.CharField(max_length=20, blank=True)

    def __str__(self):
        return self.parameter_name


class SensorParameter(models.Model):
    sensor                  = models.ForeignKey(Sensor)
    parameter               = models.ForeignKey(Parameter)
    parameter_name_userdef  = models.CharField(max_length=100, blank=False, default="Parameter")
    live_value              = models.FloatField(null=True)

    # def save(self, *args, **kwargs):
    #     default_string = str(self.sensor.name + " - " + self.parameter.parameter_name)
    #     self.parameter_name_userdef = default_string
    #     super(SensorParameter, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.sensor.name) + ' - ' + str(self.parameter)

    def __key(self):
        return self.sensor.id, self.parameter.id

    def __eq__(self, y):
        return isinstance(y, self.__class__) and self.__key() == y.__key()

    def __hash__(self):
        return hash(self.__key())

    class Meta:
        unique_together=(('sensor','parameter'),)


class Data(models.Model):
    time                = models.DateTimeField(db_index=True)
    sensor_parameter    = models.ForeignKey(SensorParameter, on_delete=models.CASCADE)
    parameter_value     = models.FloatField()

    def __str__(self):
        return str(self.time) + ' : ' + self.sensor_parameter.parameter_name_userdef + ' = ' + str(self.parameter_value)

    def __key(self):
        return self.time, self.sensor_parameter

    def __eq__(self, y):
        return isinstance(y, self.__class__) and self.__key() == y.__key()

    def __hash__(self):
        return hash(self.__key())

impedans_expert/templates/expert/chamber.html
{% extends 'old_base.html' %}
{% load staticfiles %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}
Chamber: {{chamber.chamber_name}}
{% endblock %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
{% endblock %}


{% block main_content %}

<!-- Modal block -->
<div id="editProp" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <form class="form-horizontal" id="chamber-form" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="modal-content">
                <div class="modal-header">
                    <h3>Chamber Property</h3>
                </div>
                <div class="modal-body">
                    {{ chamber_property_form|crispy }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary submit_property" id="property_submit" data-dismiss="modal">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div id="delProp" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <form class="form-horizontal" method="POST" enctype="multipart/form-data">
            <div class="modal-content">
                <div class="modal-header">
                    <h3>Delete Property</h3>
                </div>
                <div class="modal-body text-center">
                    <h6>Are you sure you want to delete this property?</h6>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary submit_property" id="property_submit" data-dismiss="modal">Delete</button>
                </div>
            </div>
        </form>
    </div>
</div>
<div id="addSensor" class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <form class="form-horizontal" method="POST" enctype="multipart/form-data">
            <div class="modal-content">
                <div class="modal-header">
                    <h3>Add Sensor</h3>
                </div>
                <div class="modal-body">
                    {{ sensor_form|crispy }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary submit_sensor" id="sensor_submit" data-dismiss="modal">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>
<!-- End modal block -->

<!-- NEW CHAMBER STARTS HERE -->
<br>
<div class="row">
    <div class="col-md-6 offset-md-1">
        <h4>
            Chamber: {{chamber.chamber_name}}
        </h4>
    </div>
</div>
<br>
<div class="row">
    <div class="col-md-5 offset-md-1">
        <div class="tableBox">
            <h6 class="card-header bg-danger text-white text-center banner">
                Chamber Properties
            </h6>
            <div class="card-body p-0 text-center mx-auto">
                <table id="miniTableProp" class="table display compact" cellspacing="0" cellpadding="0">
                    <thead>
                        <tr class="table-active">
                            <th>Property</th>
                            <th>Value</th>
                        </tr>
                    </thead>
                    <tfoot id="footerSearch">
                        <tr>
                            <th>Property</th>
                            <th>Value</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for property in chamber_properties %}
                            <tr>
                                <td>
                                    <span>{{property.property_name}}</span>
                                </td>
                                <td>
                                    <span>{{property.property_value}}</span>
                                    <span class="floatButton">
                                        <i class="far fa-edit" id="edit-property-{{property.id}}" data-id="{{property.id}}" data-toggle="modal" data-target="#editProp" title="Edit Property Name"></i>
                                        <i class="far fa-trash-alt" id="{{property.id}}" data-id="delete-{{property.id}}" data-toggle="modal" data-target="#delProp" title="Delete Property"></i>
                                    </span>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="card-block p-1 text-center mx-auto">
                    <button class="btn btn-secondary banner new-obj-button" id="add-property-to-recipe-{{recipe.id}}" data-id="new-property" data-toggle="modal" data-target="#editProp">Add Property</button>
                </div>
            </div>
        </div>
        <br>
        <div class="tableBox">
            <h6 class="card-header bg-danger text-white text-center banner">
                Sensors
            </h6>
            <div class="card-body p-0 text-center mx-auto">
                <table id="miniTableVal" class="table display compact" cellspacing="0" cellpadding="0">
                    <thead>
                        <tr class="table-active">
                            <th>Sensor</th>
                            <th>Serial No.</th>
                            <th>Type</th>
                            <th>Active</th>
                        </tr>
                    </thead>
                    <tfoot id="footerSearch">
                        <tr>
                            <th>Sensor</th>
                            <th>Serial No.</th>
                            <th>Type</th>
                            <th id="hide"></th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for sensor in sensors_list %}
                            <tr>
                                <td><a href="{% url 'sensor' sensor.id %}">{{sensor.name}}</a></td>
                                <td>{{sensor.serial_number}}</td>
                                <td>{{sensor.sensor_type}}</td>
                                {% if sensor.active %}
                                    <td><input type="checkbox" value="" checked></td>
                                {% else %}
                                    <td><input type="checkbox" value="" unchecked></td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="card-block p-1 text-center mx-auto">
                    <button class="btn btn-secondary banner new-obj-button" id="add-sensor-to-chamber-{{chamber.id}}" data-id="new-sensor" data-toggle="modal" data-target="#addSensor">Add Sensor</button>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-5">
        <h6 class="card-header bg-danger text-white text-center banner">
            Chamber Parameters
        </h6>
        <div class="card-body p-0 text-center mx-auto">
            <table id="miniTableParam" class="table display compact" cellspacing="0" cellpadding="0">
                <thead>
                    <tr class="table-active">
                        <th>Parameter</th>
                        <th>Value</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Parameter</th>
                        <th>Value</th>
                    </tr>
                </tfoot>
                <tbody>
                    {% for parameter in chamber_parameters %}
                        <tr>
                            <td>{{parameter.parameter_name_userdef}}</td>
                            <td>{{parameter.live_value}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

{% block end_scripts %}
<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="{% static 'js/mini_filter.js' %}"></script>
<script>
    $(document).ready(function() {
        $('#hide input').hide();
        $('#editProp, #delProp, #addSensor').on('show.bs.modal', function (event) {     // Watch DOM events for modal window generation
            var button = $(event.relatedTarget)                                         // Capture the button that triggered the modal

            getPropertyId = function() {
                var property_id = button.data('id')                                     // Extract the property.id from data-id attribute of the button
                return property_id;
            };

            if (getPropertyId() != "new-property") {
                var previous_property = button.parent().parent().prev().text().trim();  // Capture the existing property name to pre-fill the input field
                $("#id_property_name").val(previous_property);                          // Fill in the name input field with the existing property name
                var previous_value = button.parent().prev().text();                     // Capture the existing property value to pre-fill the input field
                $("#id_property_value").val(previous_value);                            // Fill in the value input field with the existing property value
            } else {                                                                    // If the clicked button is for a new property, reset the input fields to empty values
                $("#id_property_name").val("");
                $("#id_property_value").val("");
            };

            var inputElements = $('#id_property_name, #id_property_value')              // Capture all input elements in a form

            inputElements.keyup(function() {                                            // Detect any typing changes on either input field
                var empty = false;                                                      // Initialise a false flag, assumes there's inputs in the input fields
                inputElements.each(function() {                                         // Watch each input field for text changes
                    if ($(this).val().length == 0) {                                    // If all text in the input field is delete, set empty flag to true
                        empty = true;
                    };
                });

                if (empty) {                                                            // If the empty flag is true, disable the submit button until both input fields contain text
                    $('.submit_property').attr('disabled', 'disabled');
                } else {                                                                // If both input fields contain text, enable the submit button
                    $('.submit_property').removeAttr('disabled');
                };
            });

            $('.submit_property, .submit_sensor').click(function(event) {
                console.log("here");
                //event.preventDefault()
                event_id = $(this).attr('id');

                if (event_id == "property_submit") {
                    var operation = "modify_properties"
                    var parameter_1 = $("#id_property_name").val();                     // Extract the new property name string that was input by the user
                    var parameter_2 = $("#id_property_value").val();                    // Extract the new property value string that was input by the user
                    var parameter_3 = ""
                } else {
                    var operation = "create_sensor"
                    var parameter_1 = $("#id_name").val();                              // Extract the sensor type that was selected by the user
                    var parameter_2 = $("#id_sensor_type").val();                       // Extract the sensor type that was selected by the user
                    var parameter_3 = $("#id_serial_number").val();                     // Extract the serial number string that was input by the user
                }

                var chamber_id = '{{chamber.id}}'                                       // Pass on the chamber_id on the POST request
                
                $.post("{% url 'chamber' chamber.id %}", {                              // POST request to the chamber view
                    csrfmiddlewaretoken: '{{csrf_token}}',
                    operation: operation,
                    chamber_id: chamber_id,
                    property_id: getPropertyId(),
                    parameter_1: parameter_1,
                    parameter_2: parameter_2,
                    parameter_3: parameter_3
                }, function(data) {                                                     // After the POST request is sent and acknowledged, reload the page to reflect changes
                    location.reload();
                }).done();
            });
        });
    });
</script>
{% endblock %}